#!usr/bin/perl

#Margaret Antonio 
#Parser for .diff files to just get differentially expressed genes with significant fold change

#.diff file description: 0-test_id 1-gene_id 2-gene 3-locus 4-sample_1 5-sample_2 6-status 7-value_1 8-value_2 9-log2(fold_change) 10-p_value 11_q-value 12-significant

# To do:
#delete COLUMNS 10, 11, 12: p-value, 1_value, significant
#For each line, If COLUMN [6] !=OK then delete line
#Sort by sample_1 then break comparisons into csv files

#use Text::CSV;
use strict;
use warnings;
use Getopt::Long;

sub print_usage(){

	print "\nRequired:\n";
    print "In the command line (without a flag), input the name of the .diff file to be parsed\n";
    
    
    print "\nOptional:\n"; 
    print "--fc \t Lowest acceptable fold_change value Default: 2\n";
    print "--out \t Name of output file\n";
}


#Assign inputs to variables

our ($fc, $out);
GetOptions(
'fc:i' => \$fc,
'out:s' => \$out,
);


sub get_time() {
    my ($sec, $min, $hour, $mday, $mon, $year, $wday, $yday, $isdst) = localtime(time);
    return "$hour:$min:$sec";
}


#TEST

print print_usage(),"\n";
print "\n";

if (!$out){
	$out="parsedDiff.diff";
}
print "Output file is:  $out \n";

if (!$fc){$fc=2;}

print get_time;
print "\nReady to begin parsing file...\n\n";

#==========================================================================================

my $file = $ARGV[0] or die "Need to get input file on the command line\n";
open(FH, '<', $file) or die "Could not open '$file' $!\n";
my $fold_change;

  my @comp1; 
  my @comp2;
  my @comp3;
  my @comp4; 
  my @comp5; 
  my @comp6;
  my @comp7;
  my @comp8;
  my @comp9;
  my @comp10;

while (my $line = <FH>) {
  my @fields = split("\t",$line);
  my $fields=\@fields;
  if ($fields[6] ne "OK"){next;}
  splice @fields, 10, 4;
  if ($fields[7]==0){
  	$fold_change=0;
  }
  else{
  	$fold_change=sprintf("%.3f",$fields[8]/$fields[7]);
  }
  if ($fold_change<$fc){
  	next;
  }
  $fields[10]=$fold_change; 


  #comp1: Ad_Fli v Ad_GFP
  #comp2: Ad_Fli v shRNA_5322
  #comp3: Ad_Fli v shRNA_5324
  #comp4: Ad_Fli v shRNA_controlpassage
  #
  #comp5: Ad_GFP v shRNA_5322
  #comp6: Ad_GFP v shRNA_5324
  #comp7: Ad_GFP v shRNA_controlpassage
  #
  #comp8: shRNA_5322 v shRNA_5324
  #comp9: shRNA_5322 v shRNA_controlpassage
  #
  #comp10: shRNA_5324 v shRNA_controlpassage
  

  if ($fields[4] eq "AD_Fli"){
  	if ($fields[5] eq "Ad_GFP"){
  		push (@comp1,[@fields]);
  	}
  	elsif ($fields[5] eq "shRNA_5322"){
  		push (@comp2,[@fields]);
  	}
  	elsif ($fields[5] eq "shRNA_5324"){
  		push (@comp3,[@fields]);
  	}
  	else {#if ($fields[5] eq "shRNA_controlpassage"){
  		push (@comp4,[@fields]);
  }
}
  elsif ($fields[4] eq "Ad_GFP"){
  	if ($fields[5] eq "shRNA_5322"){
  		push (@comp5,[@fields]);
  	}
  	elsif ($fields[5] eq "shRNA_5324"){
  		push (@comp6, [@fields]);
  	}
  	else {#if ($fields[5] eq "shRNA_controlpassage"){
  		push  (@comp7, [@fields]);
    }
   }
  elsif ($fields[4] eq "shRNA_5322"){
  	if ($fields[5] eq "shRNA_5324"){
  		push (@comp8,[@fields]);
  	}
  	else {#if ($fields[5] eq "shRNA_controlpassage"){
  		push (@comp9,[@fields]);
    }
  }
  else {
  	push (@fields, @comp10);
  }
}

#print "At the prinig part";
#foreach my $line(@comp1){
	#for my $element (@$line){
	#	print $element, "\t";
	#} 
	#print "\n";
#}
my @scomp1 = sort { $b->[10] <=> $a->[10] } @comp1;
my @scomp2 = sort { $a->[10] <=> $b->[10] } @comp2;
my @scomp3 = sort { $a->[10] <=> $b->[10] } @comp3;
my @scomp4 = sort { $a->[10] <=> $b->[10] } @comp4;
my @scomp5 = sort { $a->[10] <=> $b->[10] } @comp5;
my @scomp6 = sort { $a->[10] <=> $b->[10] } @comp6;
my @scomp7 = sort { $a->[10] <=> $b->[10] } @comp7;
my @scomp8 = sort { $a->[10] <=> $b->[10] } @comp8;
my @scomp9 = sort { $a->[10] <=> $b->[10] } @comp9;
my @scomp10 = sort { $a->[10] <=> $b->[10] } @comp10;

my @header=("test_id","gene_id","gene","locus","sample_1","sample_2","status","value_1","value_2","log2(fc)","fold_change");
open my $fh, '>', "comp1.txt" or die $!;
print $fh (join("\t", @header)),"\n";
print $fh (join("\t", @$_), "\n") for @scomp1;
close $fh;

open my $fh2, '>', "comp2.txt" or die $!;
print $fh2 (join("\t", @$_), "\n") for @scomp2;
close $fh2;

open my $fh3, '>', "comp3.txt" or die $!;
print $fh3 (join("\t", @$_), "\n") for @scomp3;
close $fh3;

open my $fh4, '>', "comp4.txt" or die $!;
print $fh4 (join("\t", @$_), "\n") for @scomp4;
close $fh4;

open my $fh5, '>', "comp5.txt" or die $!;
print $fh5 (join("\t", @$_), "\n") for @scomp5;
close $fh5;

open my $fh6, '>', "comp6.txt" or die $!;
print $fh6 (join("\t", @$_), "\n") for @scomp6;
close $fh6;

open my $fh7, '>', "comp7.txt" or die $!;
print $fh7 (join("\t", @$_), "\n") for @scomp7;
close $fh7;

open my $fh8, '>', "comp8.txt" or die $!;
print $fh8 (join("\t", @$_), "\n") for @scomp8;
close $fh8;

open my $fh9, '>', "comp9.txt" or die $!;
print $fh9 (join("\t", @$_), "\n") for @scomp9;
close $fh9;

open my $fh10, '>', "comp10.txt" or die $!;
print $fh10 (join("\t", @$_), "\n") for @scomp10;
close $fh10;



print get_time;

print "Finished \n\n";

