#!usr/bin/perl

#Margaret Antonio
#Gets pathways from .tsv file that WebGestalt ouptus. Can put pathway lists into VennY


use strict;
use warnings;
use Getopt::Long;

our ($db,$out);

GetOptions(
    'db:s' => \$db,
    'out:s' =>\$out,
);


#==========================================================================================
if (!$out){
    print "Enter a name for the output files as --out <out_file>. Database name will be automatically appended.";
    die
}
if ($db eq "webgestalt"){

    my @pathways=();
    my @pathway_ids=();
    
    
    my $file = $ARGV[0] or die "Need to get input file on the command line\n";
    open(INPUT, '<', $file) or die "Could not open '$file' $!\n";
    
    while (my $line = <INPUT>) {               #Open the input file and go through each line
        
        my @fields = split("\t",$line);
        my $fields=\@fields;
        if ($fields[0] ne"KEGG pathway"){
            next;
        }
        push (@pathways,$fields[1]);
        push (@pathway_ids,$fields[2]);
        
    }
    
    close INPUT;
    
    print "\nCreating pathway name file\n";
    
    open (FH1,">$out-wb_pathways.txt");
    foreach my $path(@pathways){
        print FH1 $path, "\n";
    }
    close FH1;
    
    print "\nNow creating pathway id file\n";
    
    open (FH2,">$out_wb_pathway_ids.txt");
    foreach my $id(@pathway_ids){
        print FH2 $id, "\n";
    }
    close FH2;
    
    }

elsif ($db eq "reactome"){
    my @pathways;
    
    my $file = $ARGV[0] or die "Need to get input file on the command line\n";
    open(INPUT, '<', $file) or die "Could not open '$file' $!\n";
    
    while (my $line = <INPUT>) {               #Open the input file and go through each line
        
        my @fields = split("\t",$line);
        my $fields=\@fields;
        push (@pathways,$fields[1]);
        
    }
    
    close INPUT;
    
    print "\nCreating pathway name file\n";
    
    open (FH1,">$out-reactome_pathways.txt");
    foreach my $path(@pathways){
        print FH1 $path, "\n";
    }
    close FH1;
    
}


else{
    print "\nThat is not a supported database. Please enter -db reactome or -db webgestalt.\n" and die;
}
